version: '3.8'
services:
  user-crud:
    container_name: pawelWritesCode.user-crud.server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1234:1234"
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: pawelWritesCode.user-crud.swagger_ui
    ports:
      - "81:8080"
    volumes:
      - type: bind
        source: ./doc
        target: /usr/share/nginx/html/doc
    environment:
      API_URL: doc/schema.json
